### ISSUE TITLE
How do you set the base path for bower?

### ISSUE THREAD

**Issue by matthew-dean** [mjeanroy/rollup-plugin-bower-resolve#2]
I'm having trouble resolving bower modules. Does this resolver only look in the root directory? If so, how do I change that?

**Comment by mjeanroy** [comment]
Hi,

The resolver use bower to list the dependencies, then use the directory where the dependency is installed (which is `bower_components` by default, or a custom directory if you changed that in your `.bowerrc` configuration). You can see it [here](https://github.com/mjeanroy/rollup-plugin-bower-resolve/blob/v0.2.0/src/rollup-plugin-bower-resolve.js#L58).

What do you mean by "root directory" ?
What is your error message ?

**Comment by matthew-dean** [comment]
@mjeanroy Sorry, I did figure out it was a function of `.bowerrc` settings, and forgot to update this issue I opened. Will close.
