### ISSUE TITLE
Does this use the "main" property of "bower.json"

### ISSUE THREAD

**Issue by matthew-dean** [mjeanroy/rollup-plugin-bower-resolve#3]
I'm trying to do something simple, like import jquery from bowser. In the jQuery bower package, it has a `bower.json` file with a key/value pair of `"main": "dist/jquery.js"`. Doesn't this plugin check this for resolving the location of:
```js
import $ from 'jquery';
```
?

**Comment by mjeanroy** [comment]
Hi @matthew-dean, 
The plugin should use the `main` property of `bower.json` (see [here](https://github.com/mjeanroy/rollup-plugin-bower-resolve/blob/v0.3.0/src/rollup-plugin-bower-resolve.js#L71)). If not, then you probably found a bug.

Do you confirm the bug?

**Comment by mjeanroy** [comment]
Without updates, I'm closing the issue. Please re-open if you can reproduce the bug.
